name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Build project
        run: yarn install && yarn build

      - name: Upload COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          cos_bucket: ${{ secrets.BUCKET }}
          cos_region: ap-shanghai
          local_path: build
          remote_path: /
          clean: true